### ISSUE TITLE
Forms aren't reset after a message has been sent

### ISSUE THREAD

**Issue by rpierry** [Renerick/htmx-signalr#2]
When using signalr-send on a form element, after the send message (on form submit), the form isn't reset.  This is different from how default htmx works when applying an hx-post attribute to it.

I didn't see anything in your source that handles this specially, but I'm pretty new to all of this so I might have missed it.

Worst case I know I can hook the afterSend event and just write some script to clear the form, but I wasn't sure if you were intending to have this work just like hx-post.

Thanks!

**Comment by Renerick** [comment]
Hi there! Thanks for raising the issue!

This behavior is intended to match the behavior of official WS extension https://htmx.org/extensions/web-sockets/, which also doesn't reset forms on submit. This may change in the future with htmx 2.0, this extension will also be updated in that case.

For now, as you pointed out, hooking into afterSend with JS is your best bet

Feel free to reopen this if you got any other concerns!
